image: maven:3-openjdk-17

stages:
  - Build
  - Deploy

pre-script:
  stage: Build
  script:
    - export POSTGRESQL_HOSTNAME=$POSTGRESQL_HOSTNAME
    - export POSTGRESQL_PORT=$POSTGRESQL_PORT
    - export POSTGRESQL_DB_NAME=$POSTGRESQL_DB_NAME
    - export POSTGRESQL_DB_USER=$POSTGRESQL_DB_USER
    - export POSTGRESQL_DB_PASSWORD=$POSTGRESQL_DB_PASSWORD
    - export KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
    - export KEYCLOAK_REALM=$KEYCLOAK_REALM
    - export KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
    - export KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET
    - export COUNTRY_CODE=$COUNTRY_CODE
    - export LOCATION_SEARCH_URL=$LOCATION_SEARCH_URL
    - export SMTP_HOST=$SMTP_HOST
    - export SMTP_PORT=$SMTP_PORT
    - export SMTP_ENABLE_START_TLS=$SMTP_ENABLE_START_TLS
    - export SMTP_USERNAME=$SMTP_USERNAME
    - export SMTP_PASSWORD=$SMTP_PASSWORD
    - export INCOME_MARGIN=$INCOME_MARGIN
    - export AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_ACCOUNT_NAME
    - export AZURE_STORAGE_ENDPOINT=$AZURE_STORAGE_ENDPOINT
    - export AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_ACCOUNT_KEY
    - export AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME
    - export ALLOWED_ORIGINS=$ALLOWED_ORIGINS
    - export AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
    - docker rmi -f crew-tracker-b
    - docker system prune -a --volumes -f
    - docker build
      -t crew-tracker-b .
  only:
    - trunk



prod deploy:
  stage: Deploy
  script:
    - docker rm -f crew-tracker-backend
    - docker run
      -v /etc/timezone:/etc/timezone:ro
      -e POSTGRESQL_HOSTNAME=$POSTGRESQL_HOSTNAME
      -e AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
      -e POSTGRESQL_PORT=$POSTGRESQL_PORT
      -e POSTGRESQL_DB_NAME=$POSTGRESQL_DB_NAME
      -e POSTGRESQL_DB_USER=$POSTGRESQL_DB_USER
      -e POSTGRESQL_DB_PASSWORD=$POSTGRESQL_DB_PASSWORD
      -e KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
      -e KEYCLOAK_REALM=$KEYCLOAK_REALM
      -e KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
      -e KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET
      -e COUNTRY_CODE=$COUNTRY_CODE
      -e LOCATION_SEARCH_URL=$LOCATION_SEARCH_URL
      -e SMTP_HOST=$SMTP_HOST
      -e SMTP_PORT=$SMTP_PORT
      -e SMTP_ENABLE_START_TLS=$SMTP_ENABLE_START_TLS
      -e SMTP_USERNAME=$SMTP_USERNAME
      -e SMTP_PASSWORD=$SMTP_PASSWORD
      -e INCOME_MARGIN=$INCOME_MARGIN
      -e AZURE_STORAGE_ACCOUNT_NAME=$AZURE_STORAGE_ACCOUNT_NAME
      -e AZURE_STORAGE_ENDPOINT=$AZURE_STORAGE_ENDPOINT
      -e AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_ACCOUNT_KEY
      -e AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME
      -e ALLOWED_ORIGINS=$ALLOWED_ORIGINS
      -p 8080:8080
      --restart unless-stopped -d
      --name crew-tracker-backend crew-tracker-b
  only:
    - trunk
