apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewtracker-backend-deploy
  labels:
    app: crewtracker-backend-deploy
  namespace: crewtracker-backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crewtracker-backend-deploy
  template:
    metadata:
      labels:
        app: crewtracker-backend-deploy
    spec:
      containers:
        - name: crewtracker-backend-deploy
          image: acrworkflow1690924317472.azurecr.io/crewtracker-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ALLOWED_ORIGINS
              value: ${{env.ALLOWED_ORIGINS}}
            - name: AZURE_CLIENT_ID
              value: "${{env.AZURE_CLIENT_ID}}"
            - name: AZURE_CLIENT_SECRET
              value: ${{AZURE_CLIENT_SECRET}}
            - name: AZURE_STORAGE_ACCOUNT_KEY
              value: "$(AZURE_STORAGE_ACCOUNT_KEY)"
            - name: SMTP_HOST
              value: ${{ secrets.SMTP_HOST }}
