apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewtracker-backend-deploy
  labels:
    app: crewtracker-backend-deploy
  namespace: crewtracker-backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crewtracker-backend-deploy
  template:
    metadata:
      labels:
        app: crewtracker-backend-deploy
    spec:
      containers:
        - name: crewtracker-backend-deploy
          image: acrworkflow1690924317472.azurecr.io/crewtracker-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-host
                  key: smtp-host
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-password
                  key: smtp-password
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-port
                  key: smtp-port
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-username
                  key: smtp-username
            - name: SMTP_ENABLE_START_TLS
              valueFrom:
                secretKeyRef:
                  name: smtp-enable-start-tls
                  key: smtp-enable-start-tls
            - name: ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: allowed-origins
                  key: allowed-origins
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-client-id
                  key: azure-client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-client-secret
                  key: azure-client-secret
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-key
                  key: azure-storage-account-key
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-name
                  key: azure-storage-account-name
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-storage-connection-string
                  key: azure-storage-connection-string
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-storage-container-name
                  key: azure-storage-container-name
            - name: AZURE_STORAGE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: azure-storage-endpoint
                  key: azure-storage-endpoint
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-tenant-id
                  key: azure-tenant-id
            - name: COUNTRY_CODE
              valueFrom:
                secretKeyRef:
                  name: country-code
                  key: country-code
            - name: INCOME_MARGIN
              valueFrom:
                secretKeyRef:
                  name: income-margin
                  key: income-margin
            - name: KEYCLOAK_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-base-url
                  key: keycloak-base-url
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-id
                  key: keycloak-client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: keycloak-client-secret
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-realm
                  key: keycloak-realm
            - name: LOCATION_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: location-search-url
                  key: location-search-url
            - name: POSTGRESQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-name
                  key: postgresql-db-name
            - name: POSTGRESQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-password
                  key: postgresql-db-password
            - name: POSTGRESQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-user
                  key: postgresql-db-user
            - name: POSTGRESQL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-hostname
                  key: postgresql-hostname
            - name: POSTGRESQL_PORT
              valueFrom:
                secretKeyRef:
                  name: postgresql-port
                  key: postgresql-port
            - name: KEY_STORE
              valueFrom:
                secretKeyRef:
                  name: crewtracker-backend-tls
                  key: crewtracker-backend-tls