apiVersion: v1
kind: Service
metadata:
  name: crewtracker-backend-deploy
  namespace: crewtracker-backend-service
spec:
  selector:
    app: crewtracker-backend-deploy
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080