apiVersion: v1
kind: Service
metadata:
  name: crewtracker-backend-deploy
  namespace: crewtracker-backend
spec:
  type: LoadBalancer
  selector:
    app: crewtracker-backend-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080